#!/bin/sh
if [ $1 = "--uninstall" ]
then
	sudo julia -q -e 'using KeyCounter; uninstall(); using Pkg; Pkg.remove("KeyCounter")'
else
	sudo julia -q -e 'using KeyCounter; countkeys()' -- --user `id -u` "$@"
fi
